# Generated by Django 4.1.3 on 2023-01-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feed_back',
        ),
    ]
