# Generated by Django 4.1.3 on 2023-02-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('em1', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
